# Generated by Django 4.0.2 on 2022-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='feature_field',
            field=models.BooleanField(default=False),
        ),
    ]
