# Generated by Django 4.0.2 on 2022-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogmodel_feature_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='feature_field',
            field=models.BooleanField(default=True),
        ),
    ]
