# Generated by Django 4.0.2 on 2022-02-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_blogmodel_feature_field_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
