# Generated by Django 4.0.2 on 2022-04-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
